python scripts/train.py \
--dataset_type=ffhq_encode \
--exp_dir=experiments/33 \
--workers=8 \
--batch_size=4 \
--test_batch_size=4 \
--test_workers=8 \
--val_interval=2500 \
--save_interval=5000 \
--encoder_type=GradualStyleEncoder \
--start_from_latent_avg \
--lpips_lambda=0.8 \
--l2_lambda=1 \
--id_lambda=0.1 \
--network_pkl=pretrained_models/ffhq512-128.pkl \
--dataset_path=/workspace/ffhq_1024_mirrored
